### Site Settings ###
title               : Shivi Vats
description         : >-
                      Shivi's Portfolio and Blog
baseurl             : ""                     # Change to empty quotes if you are hosting your site at <your-username>.github.io directly
repository          : shivivas/shivivats.github.io     # Change to <your-username>/<your-username>.github.io (or remove it if you don't need remote projects)
remote_theme        : YoussefRaafatNasry/portfolYOU
open_new_tab        : true                             # Opens external URLs in new tab (works for posts, projects and navbar only)

looking_for_job: true # set it to true or false to show the relevant text at the bottom of blog posts


### Plugins ###
plugins:
  - jemoji


### Navbar Settings ###
nav_exclude:                                            # The following paths are excluded from navbar
  - pages/tags.html
  - pages/category.html
  - pages/404.html
  - pages/index.md


### Author Info ###
author:
  name              : Shivi Vats
  image             : /assets/images/Me/shivi_vats_square.jpg
# behance           : your_username
# dribbble          : your_username
  email             : shivivats7@gmail.com
# facebook          : your_username
  github            : shivivats
#  github2           : shivivats-aau
# gitlab            : your_username
  itch              : https://zarroc.itch.io
# instagram         : your_username
# kaggle            : your_username
  linkedin          : shivivats/
# medium            : your_username
# soundcloud        : your_username
# spotify           : your_username
# stackoverflow     : your_user_id
# tumblr            : your_username.tumblr.com
# twitch            : your_username
# twitter           : your_username
# vimeo             : your_username
# youtube           : your_channel_name
# keybase           : your_username


### Posts ###
permalink: /blog/:title


### Collections ###
collections:
  projects:
    output: true
    permalink: /projects/:name
  other-work:
    output: true
    permalink: /other-work/:name
  academic-work:
    output: true
    permalink: /academic-work/:name


### Disqus ###
disqus:
  shortname: your-short-name-disqus                     # Your website Shortname on disqus


### Analytics ###
analytics:
  enabled: false                                        # Set true to enable analytics
  google:
    tracking_id: your-google-tracking-id


### Buy me a coffee ###
# # See https://www.buymeacoffee.com/
# buymeacoffee:
#   enabled: false
#   username: your_username
#   color: "#007bff"
#   message: "Thank you for visiting."                    # Message to be displayed aside from the button for a few seconds.
#   description: "Support me on Buy me a coffee!"


### Defaults for collections ###
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "other-work"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "academic-work"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "posts"
    values:
      comments: false                                   # Set to true to enable disqus comments


### Exclude from processing ###
exclude:
  - README.md
  - CONTRIBUTING.md
  - LICENSE
  - "*.log"
  - Gemfile
  - Gemfile.lock
  - node_modules
  - /vendor/bundle/
  - /vendor/cache/
  - /vendor/gems/
  - /vendor/ruby/
  - /_posts/templates/
  - /_posts/todo/