# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://shivivats.github.io
title: Shivi's Portfolio and Blogs
email: shivivats.dev@gmail.com
author: Shivi Vats
description: > # "Write an awesome description for your new site here. 
  My programming portfolio, along with my more technology-focused and food-focused blogs.
copyright: 'Copyright &copy; 2021 Shivi Vats. All Rights Reserved.'
credits: 'Credits: Using the "Landing Page" Bootstrap theme, ported to Jekyll by <a href="https://github.com/swcool">Shane Weng</a>.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: twitter
    display_title: twitter
    url: https://twitter.com/shivivats7
  - title: github
    display_title: github
    url: https://github.com/shivivats
  - title: linkedin
    display_title: linkedin
    url: https://www.linkedin.com/in/shivivats/
  - title: envelope
    display_title: mail
    url: "mailto:shivivats.dev@gmail.com"